### ISSUE TITLE
Import modules from subdirectories

### ISSUE THREAD

**Issue by danielapai** [danielapai/QHF#2]
The habitat, metabolism, and visualization modules should be imported from the corresponding sub-directories. However, importing a module from a subdirectory is not trivial and currently the program does not find modules that are not in the main directory.

**Comment by mm-murphy** [comment]
I will add the following lines to the header of the `QHF.py` script after importing the `sys` module:
`sys.path.append('./habitats') `
`sys.path.append('./metabolisms') `
`sys.path.append('./visualizations')`

These paths point to (new) subdirectories within the main QHF directory, where the user will place their habitat, metabolism, and visualization module files. These lines tell python to look inside those directories. I have tested and made sure these work.

**Comment by mm-murphy** [comment]
Sorry, I did not mean to close it as completed. That was an accident. I will re-open for now, and then re-close this issue once I've uploaded and merged the updated script and directories.
